packages:
  - 'apps/*'
  - 'packages/*'
  - 'libs/*'

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - bcrypt
  - msw

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
