import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('thisisnotanemail');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).fill('test');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('test');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('test@test.fr');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByText('Le mot de passe doit contenir').click();
  await page.getByText('ConnexionSe connecterPas').click();
  await page.getByText('Le mot de passe doit contenir').click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('test123456');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByText('Identifiants incorrects').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).fill('sonik.vibea@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Sonik123');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).press('Shift+Home');
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Sonik123');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.locator('body').press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email' }).fill('sonik.vigbea@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByText('Connexion réussie').click();
  await page.getByRole('button', { name: 'Déconnexion' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sonik.vigbea@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Sonik1234');
  await expect(page.getByRole('button', { name: 'Se connecter' })).toBeVisible();
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await expect(page.getByText('Identifiants incorrects')).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sonik.vigbea@gmail.com1');
  await page.getByRole('button', { name: 'Déconnexion' }).click();
  await page.getByRole('textbox', { name: 'Mot de passe' }).fill('Sonik123');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await expect(page.getByText('Adresse email invalide')).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sonik.vigbea@gmail.com');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await expect(page.getByText('Connexion réussie')).toBeVisible();
  await page.getByRole('button', { name: 'Déconnexion' }).click();
});