export const VAN_TYPES = [
  { vanType: 'VOLKSWAGEN_ID_BUZZ', displayName: 'Volkswagen ID. Buzz', category: 'Compact', length: 4712, width: 1985, imageUrl: '/images/VOLKSWAGEN_ID_BUZZ.png' },
  { vanType: 'RENAULT_KANGOO_EXPRESS', displayName: 'Renault Kangoo Express', category: 'Compact', length: 4486, width: 1860, imageUrl: '/images/RENAULT_KANGOO_EXPRESS.png' },
  { vanType: 'FIAT_DOBLO', displayName: 'Fiat Doblo', category: 'Compact', length: 4400, width: 1832, imageUrl: '/images/FIAT_DOBLO.png' },
  { vanType: 'MERCEDES_VITO', displayName: 'Mercedes-Benz Vito', category: 'Moyen', length: 5143, width: 1928, imageUrl: '/images/MERCEDES_VITO.png' },
  { vanType: 'FORD_TRANSIT_CUSTOM_L1', displayName: 'Ford Transit Custom L1', category: 'Moyen', length: 4972, width: 1986, imageUrl: '/images/FORD_TRANSIT_CUSTOM_L1.png' },
  { vanType: 'RENAULT_MASTER_L2H2', displayName: 'Renault Master L2H2', category: 'Grand', length: 5548, width: 2070, imageUrl: '/images/RENAULT_MASTER_L2H2.png' },
  { vanType: 'CITROEN_JUMPER_L2H2', displayName: 'Citroën Jumper L2H2', category: 'Grand', length: 5413, width: 2050, imageUrl: '/images/CITROEN_JUMPER_L2H2.png' },
  { vanType: 'MERCEDES_SPRINTER_L3H2', displayName: 'Mercedes-Benz Sprinter L3H2', category: 'XL', length: 5932, width: 2020, imageUrl: '/images/MERCEDES_SPRINTER_L3H2.png' },
  { vanType: 'FIAT_DUCATO_L3H2', displayName: 'Fiat Ducato L3H2', category: 'XL', length: 5998, width: 2050, imageUrl: '/images/FIAT_DUCATO_L3H2.png' },
  { vanType: 'IVECO_DAILY_35S14_L2H2', displayName: 'Iveco Daily 35S14 L2H2', category: 'Grand', length: 5520, width: 2010, imageUrl: '/images/IVECO_DAILY_35S14_L2H2.png' },
  { vanType: 'MAN_TGE_L3H2', displayName: 'MAN TGE L3H2', category: 'XL', length: 5986, width: 2040, imageUrl: '/images/MAN_TGE_L3H2.png' },
  { vanType: 'MERCEDES_SPRINTER_L4H2', displayName: 'Mercedes-Benz Sprinter L4H2', category: 'XXL', length: 7367, width: 2020, imageUrl: '/images/MERCEDES_SPRINTER_L4H2.png' },
  { vanType: 'VOLKSWAGEN_CRAFTER_L4H2', displayName: 'Volkswagen Crafter L4H2', category: 'XXL', length: 7391, width: 2040, imageUrl: '/images/VOLKSWAGEN_CRAFTER_L4H2.png' },
  { vanType: 'MERCEDES_SPRINTER_L5H2', displayName: 'Mercedes-Benz Sprinter L5H2', category: 'XXXL', length: 7867, width: 2020, imageUrl: '/images/MERCEDES_SPRINTER_L5H2.png' },
  { vanType: 'VOLKSWAGEN_CRAFTER_L5H2', displayName: 'Volkswagen Crafter L5H2', category: 'XXXL', length: 7890, width: 2040, imageUrl: '/images/VOLKSWAGEN_CRAFTER_L5H2.png' },
  { vanType: 'RENAULT_MASTER_L3H2', displayName: 'Renault Master L3H2', category: 'XL', length: 6198, width: 2070, imageUrl: '/images/RENAULT_MASTER_L3H2.png' },
  { vanType: 'CITROEN_JUMPER_L3H2', displayName: 'Citroën Jumper L3H2', category: 'XL', length: 5998, width: 2050, imageUrl: '/images/CITROEN_JUMPER_L3H2.png' },
  { vanType: 'MAN_TGE_L4H2', displayName: 'MAN TGE L4H2', category: 'XXL', length: 7391, width: 2040, imageUrl: '/images/MAN_TGE_L4H2.png' },
  { vanType: 'IVECO_DAILY_35S14_L3H2', displayName: 'Iveco Daily 35S14 L3H2', category: 'XL', length: 6190, width: 2010, imageUrl: '/images/IVECO_DAILY_35S14_L3H2.png' },
  { vanType: 'MERCEDES_SPRINTER_L3H2_MINI_BUS', displayName: 'Mercedes-Benz Sprinter L3H2', category: 'Bus', length: 5932, width: 2020, imageUrl: '/images/MERCEDES_SPRINTER_L3H2_MINI_BUS.png' },
  { vanType: 'VOLKSWAGEN_CRAFTER_L3H2_MINI_BUS', displayName: 'Volkswagen Crafter L3H2', category: 'Bus', length: 5986, width: 2040, imageUrl: '/images/VOLKSWAGEN_CRAFTER_L3H2_MINI_BUS.png' }
];
